name: Generate smart contracts docs
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
concurrency:
  group: generate-docs
  cancel-in-progress: true
jobs:
  generate-docs:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Configure Node.js
        uses: 'actions/setup-node@v2'
        with:
          node-version: 14.19.1

      - name: Retrieve project Yarn cache
        id: cache
        uses: 'actions/cache@v2'
        with:
          path: |
            ./node_modules
          key: staging-docs-${{ hashFiles('./yarn.lock') }}

      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          yarn install --prefer-offline --frozen-lockfile 2> >(grep -v warning 1>&2)

      - name: Generate docs
        run: |
          yarn run generate

      - name: Save and push docs
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update smart contract docs'
          push: true
